export const preset2026Questions = [
  {
    id: "auto-left-starting-zone",
    label: "Did they leave starting zone?",
    type: "toggle",
    phase: "auto",
    order: 10,
    required: false,
    options: [],
  },
  {
    id: "auto-scoring-cycles",
    label: "Auto scoring cycles",
    type: "counter",
    phase: "auto",
    order: 20,
    required: false,
    options: [],
  },
  {
    id: "auto-ferry-cycles",
    label: "Auto ferry cycles",
    type: "counter",
    phase: "auto",
    order: 30,
    required: false,
    options: [],
  },
  {
    id: "auto-scoring-accuracy",
    label: "Auto scoring accuracy",
    type: "select",
    phase: "auto",
    order: 35,
    required: false,
    options: ["Low", "Medium", "High"],
  },
  {
    id: "auto-approached-tower",
    label: "Approached tower?",
    type: "toggle",
    phase: "auto",
    order: 40,
    required: false,
    options: [],
  },
  {
    id: "auto-attempted-climb",
    label: "Attempted auto climb?",
    type: "toggle",
    phase: "auto",
    order: 50,
    required: false,
    options: [],
  },
  {
    id: "auto-climb-level",
    label: "Auto climb level",
    type: "select",
    phase: "auto",
    order: 60,
    required: false,
    options: ["None", "L1", "L2", "L3"],
  },
  {
    id: "auto-climb-result",
    label: "Auto climb result",
    type: "select",
    phase: "auto",
    order: 70,
    required: false,
    options: ["Success", "Fail", "Not Attempted"],
  },
  {
    id: "teleop-scoring-cycles",
    label: "Scoring cycles",
    type: "counter",
    phase: "teleop",
    order: 110,
    required: false,
    options: [],
  },
  {
    id: "teleop-ferrying-cycles",
    label: "Ferrying cycles",
    type: "counter",
    phase: "teleop",
    order: 120,
    required: false,
    options: [],
  },
  {
    id: "teleop-scoring-accuracy",
    label: "Teleop scoring accuracy",
    type: "select",
    phase: "teleop",
    order: 125,
    required: false,
    options: ["Low", "Medium", "High"],
  },
  {
    id: "teleop-stole-from-opponent",
    label: "Did they steal from opposing alliance?",
    type: "toggle",
    phase: "teleop",
    order: 130,
    required: false,
    options: [],
  },
  {
    id: "teleop-steal-frequency",
    label: "Steal frequency",
    type: "select",
    phase: "teleop",
    order: 140,
    required: false,
    options: ["None", "Once", "Multiple", "Constant"],
  },
  {
    id: "teleop-primary-role",
    label: "Primary role",
    type: "select",
    phase: "teleop",
    order: 150,
    required: false,
    options: ["Offense", "Defense", "Support"],
  },
  {
    id: "teleop-preferred-scoring-location",
    label: "Preferred scoring location",
    type: "select",
    phase: "teleop",
    order: 160,
    required: false,
    options: ["Low", "Mid", "High"],
  },
  {
    id: "teleop-crossed-over-bump",
    label: "Crossed over bump?",
    type: "toggle",
    phase: "teleop",
    order: 165,
    required: false,
    options: [],
  },
  {
    id: "teleop-crossed-under-trench",
    label: "Went under trench?",
    type: "toggle",
    phase: "teleop",
    order: 170,
    required: false,
    options: [],
  },
  {
    id: "teleop-picked-up-from-outpost",
    label: "Picked up from outpost?",
    type: "toggle",
    phase: "teleop",
    order: 175,
    required: false,
    options: [],
  },
  {
    id: "teleop-picked-up-from-depot",
    label: "Picked up from depot?",
    type: "toggle",
    phase: "teleop",
    order: 180,
    required: false,
    options: [],
  },
  {
    id: "teleop-picked-up-from-ground",
    label: "Picked up from ground?",
    type: "toggle",
    phase: "teleop",
    order: 185,
    required: false,
    options: [],
  },
  {
    id: "endgame-attempted",
    label: "Attempted endgame?",
    type: "toggle",
    phase: "endgame",
    order: 210,
    required: false,
    options: [],
  },
  {
    id: "endgame-level",
    label: "Endgame level",
    type: "select",
    phase: "endgame",
    order: 220,
    required: false,
    options: ["None", "L1", "L2", "L3"],
  },
  {
    id: "endgame-result",
    label: "Endgame result",
    type: "select",
    phase: "endgame",
    order: 230,
    required: false,
    options: ["Success", "Fail", "Park", "Not Attempted"],
  },
  {
    id: "overall-played-defense",
    label: "Played defense?",
    type: "select",
    phase: "overall",
    order: 310,
    required: false,
    options: ["None", "Light", "Heavy"],
  },
  {
    id: "overall-defense-effectiveness",
    label: "Defense effectiveness",
    type: "select",
    phase: "overall",
    order: 320,
    required: false,
    options: ["1", "2", "3", "4", "5"],
  },
  {
    id: "overall-driver-skill",
    label: "Driver skill",
    type: "select",
    phase: "overall",
    order: 330,
    required: false,
    options: ["1", "2", "3", "4", "5"],
  },
  {
    id: "overall-robot-speed",
    label: "Robot speed",
    type: "select",
    phase: "overall",
    order: 340,
    required: false,
    options: ["Slow", "Medium", "Fast"],
  },
  {
    id: "overall-cycle-speed",
    label: "Cycle speed",
    type: "select",
    phase: "overall",
    order: 350,
    required: false,
    options: ["Slow", "Medium", "Fast"],
  },
  {
    id: "overall-reliability",
    label: "Reliability",
    type: "select",
    phase: "overall",
    order: 360,
    required: false,
    options: ["1", "2", "3", "4", "5"],
  },
  {
    id: "overall-broke-down",
    label: "Broke down?",
    type: "toggle",
    phase: "overall",
    order: 370,
    required: false,
    options: [],
  },
  {
    id: "overall-tipped-over",
    label: "Tipped over?",
    type: "toggle",
    phase: "overall",
    order: 380,
    required: false,
    options: [],
  },
  {
    id: "overall-got-beached",
    label: "Got beached?",
    type: "toggle",
    phase: "overall",
    order: 385,
    required: false,
    options: [],
  },
  {
    id: "overall-beached-frequency",
    label: "Beached frequency",
    type: "select",
    phase: "overall",
    order: 386,
    required: false,
    options: ["None", "Once", "Multiple", "Constant"],
  },
  {
    id: "overall-fouls-penalties",
    label: "Fouls or penalties committed?",
    type: "select",
    phase: "overall",
    order: 390,
    required: false,
    options: ["None", "Few", "Many"],
  },
  {
    id: "overall-pickability",
    label: "Would you pick this robot?",
    type: "select",
    phase: "overall",
    order: 400,
    required: false,
    options: ["Yes", "No", "Maybe"],
  },
];

export const defaultQuestions = preset2026Questions;

export function sortQuestions(questions) {
  return [...questions].sort((a, b) => Number(a.order || 0) - Number(b.order || 0));
}
