export const defaultQuestions = [
  {
    id: "auto-starting-line",
    label: "Auto: crossed starting line",
    type: "toggle",
    phase: "auto",
    order: 10,
    required: false,
    options: [],
  },
  {
    id: "auto-preloaded-fuel-scored",
    label: "Auto: preloaded fuel scored in active hub",
    type: "counter",
    phase: "auto",
    order: 20,
    required: false,
    options: [],
  },
  {
    id: "auto-floor-fuel-scored",
    label: "Auto: floor fuel collected and scored",
    type: "counter",
    phase: "auto",
    order: 30,
    required: false,
    options: [],
  },
  {
    id: "auto-fuel-missed",
    label: "Auto: fuel missed or bounced out",
    type: "counter",
    phase: "auto",
    order: 40,
    required: false,
    options: [],
  },
  {
    id: "auto-route",
    label: "Auto: route style",
    type: "select",
    phase: "auto",
    order: 50,
    required: false,
    options: ["No movement", "Simple mobility", "Fuel only", "Fuel plus mobility", "Partner-aware path"],
  },
  {
    id: "auto-tower-action",
    label: "Auto: tower action",
    type: "select",
    phase: "auto",
    order: 60,
    required: false,
    options: ["None", "Approached tower", "Attempted climb", "Successful climb"],
  },
  {
    id: "teleop-active-hub-fuel",
    label: "Teleop: fuel scored while hub active",
    type: "counter",
    phase: "teleop",
    order: 110,
    required: false,
    options: [],
  },
  {
    id: "teleop-inactive-hub-shots",
    label: "Teleop: shots taken while hub inactive",
    type: "counter",
    phase: "teleop",
    order: 120,
    required: false,
    options: [],
  },
  {
    id: "teleop-missed-fuel",
    label: "Teleop: fuel missed or bounced out",
    type: "counter",
    phase: "teleop",
    order: 130,
    required: false,
    options: [],
  },
  {
    id: "teleop-cycle-speed",
    label: "Teleop: cycle speed",
    type: "select",
    phase: "teleop",
    order: 140,
    required: false,
    options: ["No cycles", "Slow", "Average", "Fast", "Elite"],
  },
  {
    id: "teleop-fuel-source",
    label: "Teleop: primary fuel source",
    type: "select",
    phase: "teleop",
    order: 150,
    required: false,
    options: ["Did not collect", "Neutral zone", "Depot", "Outpost/chute", "Mixed sources"],
  },
  {
    id: "teleop-intake-quality",
    label: "Teleop: intake quality",
    type: "select",
    phase: "teleop",
    order: 160,
    required: false,
    options: ["Could not intake", "Unreliable", "Works with lining up", "Reliable", "Very fast"],
  },
  {
    id: "teleop-fuel-capacity",
    label: "Teleop: typical fuel carried per cycle",
    type: "number",
    phase: "teleop",
    order: 170,
    required: false,
    options: [],
  },
  {
    id: "teleop-obstacle-crossing",
    label: "Teleop: obstacle/trench crossing",
    type: "select",
    phase: "teleop",
    order: 180,
    required: false,
    options: ["Avoided obstacles", "Struggled", "Crossed slowly", "Crossed reliably", "Used obstacles strategically"],
  },
  {
    id: "teleop-traffic-handling",
    label: "Teleop: traffic handling",
    type: "select",
    phase: "teleop",
    order: 190,
    required: false,
    options: ["Got stuck often", "Avoided traffic", "Held lanes okay", "Moved through traffic well", "Controlled traffic"],
  },
  {
    id: "teleop-driver-control",
    label: "Teleop: driver control",
    type: "select",
    phase: "teleop",
    order: 200,
    required: false,
    options: ["Poor", "Shaky", "Solid", "Clean", "Excellent"],
  },
  {
    id: "defense-played",
    label: "Defense: played meaningful defense",
    type: "toggle",
    phase: "overall",
    order: 260,
    required: false,
    options: [],
  },
  {
    id: "defense-quality",
    label: "Defense: quality",
    type: "select",
    phase: "overall",
    order: 270,
    required: false,
    options: ["None", "Light disruption", "Forced delays", "Strong shutdown", "Penalty-heavy"],
  },
  {
    id: "defense-resistance",
    label: "Defense: how well they handled being defended",
    type: "select",
    phase: "overall",
    order: 280,
    required: false,
    options: ["Not tested", "Shut down", "Slowed down", "Mostly unaffected", "Used defense against opponent"],
  },
  {
    id: "endgame-start-time",
    label: "Endgame: seconds before match end they left to climb",
    type: "number",
    phase: "endgame",
    order: 330,
    required: false,
    options: [],
  },
  {
    id: "endgame-tower-result",
    label: "Endgame: tower result",
    type: "select",
    phase: "endgame",
    order: 340,
    required: false,
    options: ["No attempt", "Parked near tower", "Attempted and failed", "Low rung", "Middle rung", "High rung"],
  },
  {
    id: "endgame-climb-speed",
    label: "Endgame: climb speed",
    type: "select",
    phase: "endgame",
    order: 350,
    required: false,
    options: ["No climb", "Too slow", "Slow but completed", "Average", "Fast"],
  },
  {
    id: "endgame-climb-stability",
    label: "Endgame: climb stability",
    type: "select",
    phase: "endgame",
    order: 360,
    required: false,
    options: ["No climb", "Fell", "Very risky", "Stable enough", "Rock solid"],
  },
  {
    id: "endgame-partner-aware",
    label: "Endgame: left room for partners",
    type: "toggle",
    phase: "endgame",
    order: 370,
    required: false,
    options: [],
  },
  {
    id: "overall-breakdowns",
    label: "Overall: robot breakdowns or disconnects",
    type: "select",
    phase: "overall",
    order: 430,
    required: false,
    options: ["None", "Minor issue", "Lost mechanism", "Disabled briefly", "Dead robot"],
  },
  {
    id: "overall-penalties",
    label: "Overall: penalty risk",
    type: "select",
    phase: "overall",
    order: 440,
    required: false,
    options: ["Clean", "Minor risk", "Repeated contact risk", "Field damage risk", "Major fouls observed"],
  },
  {
    id: "overall-role-fit",
    label: "Overall: best alliance role",
    type: "select",
    phase: "overall",
    order: 450,
    required: false,
    options: ["Primary scorer", "Secondary scorer", "Fuel collector", "Defender", "Climb specialist", "Utility/flex"],
  },
  {
    id: "overall-pick-priority",
    label: "Overall: pick priority",
    type: "select",
    phase: "overall",
    order: 460,
    required: false,
    options: ["Avoid", "Low", "Mid", "High", "Must discuss"],
  },
  {
    id: "overall-notes",
    label: "Overall: strategy notes for picklist",
    type: "text",
    phase: "overall",
    order: 470,
    required: false,
    options: [],
  },
];

export function sortQuestions(questions) {
  return [...questions].sort((a, b) => Number(a.order || 0) - Number(b.order || 0));
}
