export const defaultQuestions = [
  {
    id: "auto-mobility",
    label: "Auto: robot moved from starting area",
    type: "toggle",
    phase: "auto",
    order: 10,
    required: false,
    options: [],
  },
  {
    id: "auto-scored",
    label: "Auto: game pieces scored",
    type: "counter",
    phase: "auto",
    order: 20,
    required: false,
    options: [],
  },
  {
    id: "auto-missed",
    label: "Auto: missed scoring attempts",
    type: "counter",
    phase: "auto",
    order: 30,
    required: false,
    options: [],
  },
  {
    id: "teleop-scored",
    label: "Teleop: game pieces scored",
    type: "counter",
    phase: "teleop",
    order: 110,
    required: false,
    options: [],
  },
  {
    id: "teleop-missed",
    label: "Teleop: missed scoring attempts",
    type: "counter",
    phase: "teleop",
    order: 120,
    required: false,
    options: [],
  },
  {
    id: "teleop-cycle-speed",
    label: "Teleop: cycle speed",
    type: "select",
    phase: "teleop",
    order: 130,
    required: false,
    options: ["No cycles", "Slow", "Average", "Fast", "Elite"],
  },
  {
    id: "teleop-intake-quality",
    label: "Teleop: intake/collection quality",
    type: "select",
    phase: "teleop",
    order: 140,
    required: false,
    options: ["Could not collect", "Unreliable", "Average", "Reliable", "Very fast"],
  },
  {
    id: "defense-quality",
    label: "Overall: defense quality",
    type: "select",
    phase: "overall",
    order: 230,
    required: false,
    options: ["None", "Light", "Useful", "Strong", "Penalty-heavy"],
  },
  {
    id: "driver-control",
    label: "Overall: driver control",
    type: "select",
    phase: "overall",
    order: 240,
    required: false,
    options: ["Poor", "Shaky", "Solid", "Clean", "Excellent"],
  },
  {
    id: "endgame-result",
    label: "Endgame: final result",
    type: "select",
    phase: "endgame",
    order: 330,
    required: false,
    options: ["No attempt", "Parked", "Attempted and failed", "Partial success", "Full success"],
  },
  {
    id: "endgame-speed",
    label: "Endgame: speed",
    type: "select",
    phase: "endgame",
    order: 340,
    required: false,
    options: ["No attempt", "Too slow", "Slow", "Average", "Fast"],
  },
  {
    id: "overall-reliability",
    label: "Overall: reliability",
    type: "select",
    phase: "overall",
    order: 430,
    required: false,
    options: ["Dead robot", "Major issue", "Minor issue", "Reliable", "Rock solid"],
  },
  {
    id: "overall-pick-priority",
    label: "Overall: pick priority",
    type: "select",
    phase: "overall",
    order: 440,
    required: false,
    options: ["Avoid", "Low", "Mid", "High", "Must discuss"],
  },
  {
    id: "overall-notes",
    label: "Overall: strategy notes",
    type: "text",
    phase: "overall",
    order: 450,
    required: false,
    options: [],
  },
];

export function sortQuestions(questions) {
  return [...questions].sort((a, b) => Number(a.order || 0) - Number(b.order || 0));
}
